version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:10"
      timezone: Europe/Paris
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /frontend-demo
    schedule:
      interval: weekly
      day: monday
      time: "06:20"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
