use crate::generator::LicenseKind;

pub fn readme(project_name: &str) -> String {
    format!(
        "# {project_name}\n\n\
One-line value proposition for {project_name}.\n\n\
## Why it exists\n\n\
Explain the pain point this project solves and why someone should care.\n\n\
## Install\n\n\
Add installation instructions here.\n\n\
## Usage\n\n\
```bash\n\
{project_name} --help\n\
```\n\n\
## Contributing\n\n\
Please read [CONTRIBUTING.md](CONTRIBUTING.md) before opening a pull request.\n\n\
## Security\n\n\
Please report vulnerabilities according to [SECURITY.md](SECURITY.md).\n\n\
## License\n\n\
This project is licensed under the terms described in [LICENSE](LICENSE).\n"
    )
}

pub fn license_text(kind: LicenseKind, owner: &str, year: i32) -> String {
    match kind {
        LicenseKind::Mit => mit_license(owner, year),
        LicenseKind::Apache2 => apache_license(owner, year),
    }
}

pub fn contributing(project_name: &str) -> String {
    format!(
        "# Contributing to {project_name}\n\n\
Thanks for considering a contribution.\n\n\
## Ground rules\n\n\
- Be respectful and constructive.\n\
- Prefer small pull requests with a clear purpose.\n\
- Open an issue before large changes so we can align early.\n\n\
## Development flow\n\n\
1. Fork the repository.\n\
2. Create a focused branch.\n\
3. Add or update tests when behavior changes.\n\
4. Open a pull request with context, screenshots, or logs when helpful.\n\n\
## Pull request checklist\n\n\
- The change solves one clear problem.\n\
- Documentation was updated when needed.\n\
- Tests were added or existing tests still make sense.\n"
    )
}

pub fn code_of_conduct(project_name: &str) -> String {
    format!(
        "# Code of Conduct\n\n\
## Our commitment\n\n\
We want {project_name} to be a welcoming space for maintainers, contributors, and users.\n\n\
## Expected behavior\n\n\
- Show empathy and respect.\n\
- Give feedback that is specific and kind.\n\
- Assume good intent, then clarify when something feels off.\n\n\
## Unacceptable behavior\n\n\
- Harassment or personal attacks\n\
- Trolling or repeated bad-faith disruption\n\
- Publishing private information without consent\n\n\
## Reporting\n\n\
If you experience or witness harmful behavior, contact the maintainers privately.\n"
    )
}

pub fn security_policy(project_name: &str) -> String {
    format!(
        "# Security Policy\n\n\
Thanks for helping keep {project_name} safe.\n\n\
## Reporting a vulnerability\n\n\
Please do not open a public issue for security-sensitive bugs.\n\n\
Instead, contact the maintainers privately and include:\n\n\
- a description of the issue\n\
- steps to reproduce it\n\
- impact and affected versions\n\
- any suggested mitigation if you have one\n\n\
We will acknowledge the report quickly and work with you on a responsible disclosure timeline.\n"
    )
}

pub fn changelog() -> String {
    String::from(
        "# Changelog\n\n\
All notable changes to this project will be documented in this file.\n\n\
## Unreleased\n\n\
- Initial scaffold generated by ossify\n",
    )
}

pub fn bug_report_template(project_name: &str) -> String {
    format!(
        "---\n\
name: Bug report\n\
about: Report a reproducible bug in {project_name}\n\
title: \"[bug] \"\n\
labels: bug\n\
assignees: \"\"\n\
---\n\n\
## Summary\n\n\
Describe the bug clearly.\n\n\
## Steps to reproduce\n\n\
1. \n\
2. \n\
3. \n\n\
## Expected behavior\n\n\
What did you expect to happen?\n\n\
## Environment\n\n\
- OS:\n\
- Version:\n\
- Relevant logs:\n"
    )
}

pub fn feature_request_template(project_name: &str) -> String {
    format!(
        "---\n\
name: Feature request\n\
about: Suggest an improvement for {project_name}\n\
title: \"[feature] \"\n\
labels: enhancement\n\
assignees: \"\"\n\
---\n\n\
## Problem\n\n\
What is painful today?\n\n\
## Proposed solution\n\n\
What would you like to happen?\n\n\
## Alternatives considered\n\n\
What other options did you explore?\n"
    )
}

pub fn pull_request_template() -> String {
    String::from(
        "## What changed\n\n\
Explain the change in a few lines.\n\n\
## Why it matters\n\n\
Describe the user or maintainer impact.\n\n\
## Checklist\n\n\
- [ ] I tested the change\n\
- [ ] I updated docs when needed\n\
- [ ] I kept the diff focused\n",
    )
}

pub fn ci_workflow() -> String {
    String::from(
        "name: CI\n\n\
on:\n\
  push:\n\
    branches: [main]\n\
  pull_request:\n\n\
jobs:\n\
  build:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - name: Set up Rust\n\
        uses: dtolnay/rust-toolchain@stable\n\
      - name: Cache cargo\n\
        uses: Swatinem/rust-cache@v2\n\
      - name: Check\n\
        run: cargo check\n\
      - name: Test\n\
        run: cargo test\n",
    )
}

fn mit_license(owner: &str, year: i32) -> String {
    format!(
        "MIT License\n\n\
Copyright (c) {year} {owner}\n\n\
Permission is hereby granted, free of charge, to any person obtaining a copy\n\
of this software and associated documentation files (the \"Software\"), to deal\n\
in the Software without restriction, including without limitation the rights\n\
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n\
copies of the Software, and to permit persons to whom the Software is\n\
furnished to do so, subject to the following conditions:\n\n\
The above copyright notice and this permission notice shall be included in all\n\
copies or substantial portions of the Software.\n\n\
THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n\
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n\
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n\
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n\
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n\
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n\
SOFTWARE.\n"
    )
}

fn apache_license(owner: &str, year: i32) -> String {
    format!(
        "Apache License\n\
Version 2.0, January 2004\n\
http://www.apache.org/licenses/\n\n\
Copyright {year} {owner}\n\n\
Licensed under the Apache License, Version 2.0 (the \"License\");\n\
you may not use this file except in compliance with the License.\n\
You may obtain a copy of the License at\n\n\
    http://www.apache.org/licenses/LICENSE-2.0\n\n\
Unless required by applicable law or agreed to in writing, software\n\
distributed under the License is distributed on an \"AS IS\" BASIS,\n\
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n\
See the License for the specific language governing permissions and\n\
limitations under the License.\n"
    )
}
