use crate::generator::LicenseKind;
use crate::project::{ProjectContext, ProjectKind};

pub fn readme(project: &ProjectContext) -> String {
    format!(
        "# {}\n\n\
{} is a {} {} project.\n\n\
## Why it exists\n\n\
Explain the problem this project solves, who it helps, and why somebody should trust it in production or contribution workflows.\n\n\
## Install\n\n\
```bash\n\
{}\n\
```\n\n\
## Usage\n\n\
```bash\n\
{}\n\
```\n\n\
## Examples\n\n\
Add a copy-paste example here, or point people to `examples/` with one concrete path.\n\n\
## Development\n\n\
```bash\n\
{}\n\
```\n\n\
## Quality checks\n\n\
```bash\n\
{}\n\
```\n\n\
## Contributing\n\n\
Please read [CONTRIBUTING.md](CONTRIBUTING.md) before opening a pull request.\n\n\
## Security\n\n\
Please report vulnerabilities according to [SECURITY.md](SECURITY.md).\n\n\
## License\n\n\
This project is licensed under the terms described in [LICENSE](LICENSE).\n",
        project.name,
        project.name,
        project.kind.display_name(),
        project.profile.display_name(),
        project.install_snippet(),
        project.usage_snippet(),
        project.test_snippet(),
        project.lint_snippet(),
    )
}

pub fn license_text(kind: LicenseKind, owner: &str, year: i32) -> String {
    match kind {
        LicenseKind::Mit => mit_license(owner, year),
        LicenseKind::Apache2 => apache_license(owner, year),
    }
}

pub fn contributing(project: &ProjectContext) -> String {
    format!(
        "# Contributing to {}\n\n\
Thanks for considering a contribution.\n\n\
## Before you start\n\n\
- Open an issue before large changes so we can align early.\n\
- Prefer focused pull requests over broad rewrites.\n\
- Keep docs and examples in sync with behavior changes.\n\n\
## Local workflow\n\n\
1. Fork the repository.\n\
2. Create a focused branch.\n\
3. Run tests: `{}`.\n\
4. Run quality checks when available: `{}`.\n\
5. Open a pull request with context, tradeoffs, and verification notes.\n\n\
## Pull request checklist\n\n\
- The change solves one clear problem.\n\
- Documentation or examples were updated when needed.\n\
- Tests were added or existing tests still cover the behavior.\n\
- The diff stays focused and reviewable.\n",
        project.name,
        project.test_snippet(),
        project.lint_snippet(),
    )
}

pub fn code_of_conduct(project_name: &str) -> String {
    format!(
        "# Code of Conduct\n\n\
## Our commitment\n\n\
We want {project_name} to be a welcoming space for maintainers, contributors, and users.\n\n\
## Expected behavior\n\n\
- Show empathy and respect.\n\
- Give feedback that is specific and kind.\n\
- Assume good intent, then clarify when something feels off.\n\n\
## Unacceptable behavior\n\n\
- Harassment or personal attacks\n\
- Trolling or repeated bad-faith disruption\n\
- Publishing private information without consent\n\n\
## Reporting\n\n\
If you experience or witness harmful behavior, contact the maintainers privately.\n"
    )
}

pub fn security_policy(project_name: &str) -> String {
    format!(
        "# Security Policy\n\n\
Thanks for helping keep {project_name} safe.\n\n\
## Reporting a vulnerability\n\n\
Please do not open a public issue for security-sensitive bugs.\n\n\
Instead, contact the maintainers privately and include:\n\n\
- a description of the issue\n\
- steps to reproduce it\n\
- impact and affected versions\n\
- any suggested mitigation if you have one\n\n\
We will acknowledge the report quickly and work with you on a responsible disclosure timeline.\n"
    )
}

pub fn changelog() -> String {
    String::from(
        "# Changelog\n\n\
All notable changes to this project will be documented in this file.\n\n\
The format is based on Keep a Changelog.\n\n\
## Unreleased\n\n\
- Initial scaffold generated by ossify\n",
    )
}

pub fn bug_report_template(project_name: &str) -> String {
    format!(
        "---\n\
name: Bug report\n\
about: Report a reproducible bug in {project_name}\n\
title: \"[bug] \"\n\
labels: bug\n\
assignees: \"\"\n\
---\n\n\
## Summary\n\n\
Describe the bug clearly.\n\n\
## Steps to reproduce\n\n\
1. \n\
2. \n\
3. \n\n\
## Expected behavior\n\n\
What did you expect to happen?\n\n\
## Environment\n\n\
- OS:\n\
- Version:\n\
- Relevant logs:\n"
    )
}

pub fn feature_request_template(project_name: &str) -> String {
    format!(
        "---\n\
name: Feature request\n\
about: Suggest an improvement for {project_name}\n\
title: \"[feature] \"\n\
labels: enhancement\n\
assignees: \"\"\n\
---\n\n\
## Problem\n\n\
What is painful today?\n\n\
## Proposed solution\n\n\
What would you like to happen?\n\n\
## Alternatives considered\n\n\
What other options did you explore?\n"
    )
}

pub fn pull_request_template() -> String {
    String::from(
        "## What changed\n\n\
Explain the change in a few lines.\n\n\
## Why it matters\n\n\
Describe the user or maintainer impact.\n\n\
## Validation\n\n\
Describe what you tested locally and how reviewers can verify the change.\n\n\
## Checklist\n\n\
- [ ] I tested the change\n\
- [ ] I updated docs or examples when needed\n\
- [ ] I kept the diff focused\n",
    )
}

pub fn codeowners(owner: &str) -> Option<String> {
    let handle = github_handle(owner)?;
    Some(format!(
        "# Global owners for repository review\n\
* @{handle}\n\
.github/ @{handle}\n"
    ))
}

pub fn funding_file(spec: Option<&str>) -> Option<String> {
    let spec = spec?.trim();
    let (provider, value) = spec.split_once(':')?;
    let value = value.trim();
    if value.is_empty() {
        return None;
    }

    match provider.trim().to_lowercase().as_str() {
        "github" => Some(format!("github: [{value}]\n")),
        "open_collective" => Some(format!("open_collective: {value}\n")),
        "patreon" => Some(format!("patreon: {value}\n")),
        "ko_fi" => Some(format!("ko_fi: {value}\n")),
        "custom" => Some(format!("custom: [{value}]\n")),
        _ => None,
    }
}

pub fn ci_workflow(project: &ProjectContext) -> String {
    match project.kind {
        ProjectKind::Rust => String::from(
            "name: CI\n\n\
on:\n\
  push:\n\
    branches: [main]\n\
  pull_request:\n\n\
jobs:\n\
  verify:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - name: Set up Rust\n\
        uses: dtolnay/rust-toolchain@stable\n\
      - name: Cache cargo\n\
        uses: Swatinem/rust-cache@v2\n\
      - name: Format check\n\
        run: cargo fmt --check\n\
      - name: Lint\n\
        run: cargo clippy --all-targets --all-features -- -D warnings\n\
      - name: Test\n\
        run: cargo test\n\
      - name: Build\n\
        run: cargo build --release\n",
        ),
        ProjectKind::Node => String::from(
            "name: CI\n\n\
on:\n\
  push:\n\
    branches: [main]\n\
  pull_request:\n\n\
jobs:\n\
  verify:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - name: Set up Node.js\n\
        uses: actions/setup-node@v4\n\
        with:\n\
          node-version: 20\n\
          cache: npm\n\
      - name: Install dependencies\n\
        run: npm install\n\
      - name: Lint\n\
        run: npm run lint --if-present\n\
      - name: Test\n\
        run: npm test --if-present\n\
      - name: Build\n\
        run: npm run build --if-present\n",
        ),
        ProjectKind::Python => String::from(
            "name: CI\n\n\
on:\n\
  push:\n\
    branches: [main]\n\
  pull_request:\n\n\
jobs:\n\
  verify:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - name: Set up Python\n\
        uses: actions/setup-python@v5\n\
        with:\n\
          python-version: '3.12'\n\
      - name: Install project\n\
        run: |\n\
          python -m pip install --upgrade pip\n\
          python -m pip install -e .\n\
          python -m pip install pytest ruff\n\
      - name: Lint\n\
        run: ruff check .\n\
      - name: Test\n\
        run: python -m pytest\n",
        ),
        ProjectKind::Go => String::from(
            "name: CI\n\n\
on:\n\
  push:\n\
    branches: [main]\n\
  pull_request:\n\n\
jobs:\n\
  verify:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - name: Set up Go\n\
        uses: actions/setup-go@v5\n\
        with:\n\
          go-version: '1.23'\n\
      - name: Format check\n\
        run: test -z \"$(gofmt -l .)\"\n\
      - name: Test\n\
        run: go test ./...\n\
      - name: Build\n\
        run: go build ./...\n",
        ),
        ProjectKind::Unknown => String::from(
            "name: CI\n\n\
on:\n\
  push:\n\
    branches: [main]\n\
  pull_request:\n\n\
jobs:\n\
  verify:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - name: Placeholder verification\n\
        run: echo \"Replace this workflow with the real build and test steps for your project.\"\n",
        ),
    }
}

pub fn dependabot(project: &ProjectContext) -> String {
    let ecosystem = project.kind.package_ecosystem().unwrap_or("github-actions");
    format!(
        "version: 2\nupdates:\n  - package-ecosystem: {ecosystem}\n    directory: \"/\"\n    schedule:\n      interval: weekly\n  - package-ecosystem: github-actions\n    directory: \"/\"\n    schedule:\n      interval: weekly\n"
    )
}

pub fn release_workflow(project: &ProjectContext) -> String {
    match project.kind {
        ProjectKind::Rust => String::from(
            "name: Release\n\n\
on:\n\
  push:\n\
    tags:\n\
      - \"v*\"\n\
  workflow_dispatch:\n\n\
permissions:\n\
  contents: write\n\n\
jobs:\n\
  build:\n\
    name: build-${{ matrix.target }}\n\
    runs-on: ${{ matrix.os }}\n\
    strategy:\n\
      fail-fast: false\n\
      matrix:\n\
        include:\n\
          - os: ubuntu-latest\n\
            target: x86_64-unknown-linux-gnu\n\
            archive_name: release-linux.tar.gz\n\
            binary_name: ossify\n\
          - os: macos-latest\n\
            target: x86_64-apple-darwin\n\
            archive_name: release-macos.tar.gz\n\
            binary_name: ossify\n\
          - os: windows-latest\n\
            target: x86_64-pc-windows-msvc\n\
            archive_name: release-windows.zip\n\
            binary_name: ossify.exe\n\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - uses: dtolnay/rust-toolchain@stable\n\
        with:\n\
          targets: ${{ matrix.target }}\n\
      - uses: Swatinem/rust-cache@v2\n\
      - name: Build release binary\n\
        run: cargo build --release --target ${{ matrix.target }}\n\
      - name: Package release archive (unix)\n\
        if: runner.os != 'Windows'\n\
        run: |\n\
          mkdir -p dist\n\
          cp README.md LICENSE dist/\n\
          cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} dist/${{ matrix.binary_name }}\n\
          tar -czf ${{ matrix.archive_name }} -C dist .\n\
      - name: Package release archive (windows)\n\
        if: runner.os == 'Windows'\n\
        shell: pwsh\n\
        run: |\n\
          New-Item -ItemType Directory -Path dist -Force | Out-Null\n\
          Copy-Item README.md dist\\README.md\n\
          Copy-Item LICENSE dist\\LICENSE\n\
          Copy-Item target/${{ matrix.target }}/release/${{ matrix.binary_name }} dist\\${{ matrix.binary_name }}\n\
          Compress-Archive -Path dist\\* -DestinationPath ${{ matrix.archive_name }}\n\
      - name: Upload release artifact\n\
        uses: actions/upload-artifact@v4\n\
        with:\n\
          name: ${{ matrix.archive_name }}\n\
          path: ${{ matrix.archive_name }}\n\n\
  publish:\n\
    needs: build\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/download-artifact@v4\n\
        with:\n\
          path: dist\n\
      - uses: softprops/action-gh-release@v2\n\
        with:\n\
          files: |\n\
            dist/**/*.zip\n\
            dist/**/*.tar.gz\n\
          generate_release_notes: true\n",
        ),
        ProjectKind::Node => String::from(
            "name: Release\n\n\
on:\n\
  push:\n\
    tags:\n\
      - \"v*\"\n\
  workflow_dispatch:\n\n\
permissions:\n\
  contents: write\n\n\
jobs:\n\
  publish:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - uses: actions/setup-node@v4\n\
        with:\n\
          node-version: 20\n\
          cache: npm\n\
      - run: npm install\n\
      - run: npm test --if-present\n\
      - run: npm pack\n\
      - uses: softprops/action-gh-release@v2\n\
        with:\n\
          files: |\n\
            *.tgz\n\
          generate_release_notes: true\n",
        ),
        ProjectKind::Python => String::from(
            "name: Release\n\n\
on:\n\
  push:\n\
    tags:\n\
      - \"v*\"\n\
  workflow_dispatch:\n\n\
permissions:\n\
  contents: write\n\n\
jobs:\n\
  publish:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - uses: actions/setup-python@v5\n\
        with:\n\
          python-version: '3.12'\n\
      - run: |\n\
          python -m pip install --upgrade pip\n\
          python -m pip install build\n\
          python -m build\n\
      - uses: softprops/action-gh-release@v2\n\
        with:\n\
          files: |\n\
            dist/*\n\
          generate_release_notes: true\n",
        ),
        ProjectKind::Go => String::from(
            "name: Release\n\n\
on:\n\
  push:\n\
    tags:\n\
      - \"v*\"\n\
  workflow_dispatch:\n\n\
permissions:\n\
  contents: write\n\n\
jobs:\n\
  publish:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - uses: actions/setup-go@v5\n\
        with:\n\
          go-version: '1.23'\n\
      - run: go test ./...\n\
      - run: go build ./...\n\
      - uses: softprops/action-gh-release@v2\n\
        with:\n\
          generate_release_notes: true\n",
        ),
        ProjectKind::Unknown => String::from(
            "name: Release\n\n\
on:\n\
  push:\n\
    tags:\n\
      - \"v*\"\n\
  workflow_dispatch:\n\n\
permissions:\n\
  contents: write\n\n\
jobs:\n\
  publish:\n\
    runs-on: ubuntu-latest\n\
    steps:\n\
      - uses: actions/checkout@v4\n\
      - uses: softprops/action-gh-release@v2\n\
        with:\n\
          generate_release_notes: true\n",
        ),
    }
}

fn github_handle(owner: &str) -> Option<String> {
    let trimmed = owner.trim().trim_start_matches('@');
    if trimmed.is_empty()
        || !trimmed
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '-' || ch == '_')
    {
        return None;
    }

    Some(trimmed.to_owned())
}

fn mit_license(owner: &str, year: i32) -> String {
    format!(
        "MIT License\n\n\
Copyright (c) {year} {owner}\n\n\
Permission is hereby granted, free of charge, to any person obtaining a copy\n\
of this software and associated documentation files (the \"Software\"), to deal\n\
in the Software without restriction, including without limitation the rights\n\
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n\
copies of the Software, and to permit persons to whom the Software is\n\
furnished to do so, subject to the following conditions:\n\n\
The above copyright notice and this permission notice shall be included in all\n\
copies or substantial portions of the Software.\n\n\
THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n\
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n\
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n\
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n\
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n\
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n\
SOFTWARE.\n"
    )
}

fn apache_license(owner: &str, year: i32) -> String {
    format!(
        "Apache License\n\
Version 2.0, January 2004\n\
http://www.apache.org/licenses/\n\n\
Copyright {year} {owner}\n\n\
Licensed under the Apache License, Version 2.0 (the \"License\");\n\
you may not use this file except in compliance with the License.\n\
You may obtain a copy of the License at\n\n\
    http://www.apache.org/licenses/LICENSE-2.0\n\n\
Unless required by applicable law or agreed to in writing, software\n\
distributed under the License is distributed on an \"AS IS\" BASIS,\n\
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n\
See the License for the specific language governing permissions and\n\
limitations under the License.\n"
    )
}
